---
abstract: 'a trivial caching layer around an C<IO::Async::Resolver>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::Loop: '0'
  IO::Async::Test: '0'
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Async-Resolver-StupidCache
provides:
  IO::Async::Resolver::StupidCache:
    file: lib/IO/Async/Resolver/StupidCache.pm
    version: '0.01'
requires:
  IO::Async::Notifier: '0'
  IO::Async::Resolver: '0'
  Struct::Dumb: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
